#
# format:
#     {key: (English, Hindi)}
#
dictionary = {
    'title': ('title', 'VkbVy'),
    'description': ('description', 'O;k[;ku'),
    'teacher': ('teacher', 'xq:'),
    'author': ('author', 'ys[kd'),
    'uploaded_by': ('uploaded by (person name)', 'XXX'),
    'author_unknown': ('author unknown', 'vKkr ys[kd'),
    'teacher_author': ('teacher/author', 'xq:/ys[kd'),
    'file_to_upload': ('file to upload', 'ikB dk uke'),
    'students_concerned': ('students concerned', 'lacaf?kr Nk='),
    'unzip': ('unzip? check this if you are uploading a zip file that must be unziped at the repository to recover the contents of the object.  this is used to upload an object that consists of multiple files or directories. (leave it blank if you don\'t know what this is for.)', 'XXX'),
    'submit_title': ('Submit Content To the Central Repository',
                     "dsU}h; dks'k esa ikB mifLFkr djsa"),
    'upload': ('Upload', 'HksfTk,'),
    'clear_all': ('Clear All', 'lc lkQ djsa'),
    'leave_blank':("If you're unsure about any fields on this page, leave them blank.", ";fn dksb tokc vfuf'pr gks rks mls uk Hkjsa"),
    'thumbnail1': ('thumbnail image 1 (recommended use: a small image):',
                   "NksVk fp= 1 fuZnsf'kr mi;ksx ,d NksVk fp="),
    'thumbnail2': ('thumbnail image 2 (recommended use: an author picture):',
                   "NksVk fp= 2 fuZnsf'kr mi;ksx ,d ys[kd dk fp= "),
    'thumbnail3': ('thumbnail image 3 (recommended use: a larger image):',
                   "NksVk fp= 3 fuZnsf'kr mi;ksx ,d cM+k fp="),
    'thumbnail4': ('thumbnail image 4 (recommended use: a larger image):',
                   "NksVk fp= 4 fuZnsf'kr mi;ksx ,d cM+k fp="),
    'excerpt1': ('excerpt file 1', 'XXX'),
    'excerpt2': ('excerpt file 2', 'XXX'),
    'excerpt3': ('excerpt file 3', 'XXX'),
    'excerpt4': ('excerpt file 4', 'XXX'),
    'subjects': ('subjects (check all that apply)', 'fo"k; (ykxq gksus okykksa dks fpUfgr djsa)'),
    'english': ('English', 'vaxzsth'),
    'hindi': ('Hindi', 'fganh'),
    'sanskrit': ('Sanskrit', 'laLd`r'),
    'science': ('science', 'foKku'),
    'physics': ('physics', 'Hksssksfrdh'),
    'chemistry': ('chemistry', 'jlk;u foKku'),
    'astronomy': ('astronomy', "[kxksy 'kkL="),
    'biology': ('biology', 'tho foKku'),
    'mathematics': ('mathematics', 'xf.kr'),
    'arithmetic': ('arithmetic', 'vaadxf.kr'),
    'algebra': ('algebra', 'chtxf.kr'),
    'geometry': ('geometry', 'js[kkxf.kr'),
    'history': ('history', 'bfrgkl'),
    'social_studies': ('social studies', 'lekt foKku '),
    'home_science': ('home science', "x``g 'kkL="),
    'agriculture': ('agriculture', '[ksrh'),
    'general_knowledge': ('general knowledge', 'lkekU; Kku'),
    'food_and_nutrition': ('food and nutrition', 'XXX'),
    'arts_and_crafts': ('arts and crafts', 'XXX'),
    'computer_literacy': ('computer literacy', 'daI;wVj lk{kjrk'),
    'games': ('games', '[ksy'),
    'stories': ('stories', 'dgkfu;kaaW'),
    'other_subject': ('other subject (specify)', 'vU; fo"k; (crk;sa)'),
    'content_type': ('content type', 'XXX'),
    'unknown': ('unknown', 'vKkr'),
    'lecture': ('lecture', 'ikB'),
    'courseware': ('courseware', 'XXX'),
    'communication': ('communication', 'lapkj'),
    'chat': ('chat', 'ckr'),
    'student_projects': ('student_projects', 'XXX'),
    'homework_submission': ('homework_submission', 'XXX'),
    'homework_feedback': ('homework_feedback', 'XXX'),
    'questions': ('questions', 'loky'),
    'answers': ('answers', 'tokc'),
    'social_entertainment': ('social_entertainment', 'lekftd euksjatu'),
    'exam': ('exam', 'ifj{kk'),
    'information': ('information', 'lwpuk'),
    'scratch_space': ('scratch_space', 'XXX'),
    'tmp': ('tmp', 'XXX'),
    'other': ('other', 'vU;'),
    'language': ('language (check all that apply)', 'Hkk"kk;sa  (ykxq gksus okykksa dks fpUfgr djsa)'), #Confirm
    'other_language': ('other language (specify)', 'vU; Hkk"kk;sa (crk;sa)'),
    'for_class': ('for class', 'd>k dss fy;s'),
    'preschool': ('preschool', 'XXX'),
    '0': ('0', '0'),
    '1': ('1', '1'),
    '2': ('2', '2'),
    '3': ('3', '3'),
    '4': ('4', '4'),
    '5': ('5', '5'),
    '6': ('6', '6'),
    '7': ('7', '7'),
    '8': ('8', '8'),
    '9': ('9', '9'),

    '10': ('10', '10'),
    '11': ('11', '11'),
    '12': ('12', '12'),
    '13': ('13', '13'),
    '14': ('14', '14'),
    '15': ('15', '15'),
    '16': ('16', '16'),
    '17': ('17', '17'),
    '18': ('18', '18'),
    '19': ('19', '19'),

    '20': ('20', '20'),
    '21': ('21', '21'),
    '22': ('22', '22'),
    '23': ('23', '23'),
    '24': ('24', '24'),
    '25': ('25', '25'),
    '26': ('26', '26'),
    '27': ('27', '27'),
    '28': ('28', '28'),
    '29': ('29', '29'),

    '30': ('30', '30'),
    '31': ('31', '31'),
    '32': ('32', '32'),
    '33': ('33', '33'),
    '34': ('34', '34'),
    '35': ('35', '35'),
    '36': ('36', '36'),
    '37': ('37', '37'),
    '38': ('38', '38'),
    '39': ('39', '39'),

    '40': ('40', '40'),
    '41': ('41', '41'),
    '42': ('42', '42'),
    '43': ('43', '43'),
    '44': ('44', '44'),
    '45': ('45', '45'),
    '46': ('46', '46'),
    '47': ('47', '47'),
    '48': ('48', '48'),
    '49': ('49', '49'),

    '50': ('50', '50'),
    '51': ('51', '51'),
    '52': ('52', '52'),
    '53': ('53', '53'),
    '54': ('54', '54'),
    '55': ('55', '55'),
    '56': ('56', '56'),
    '57': ('57', '57'),
    '58': ('58', '58'),
    '59': ('59', '59'),

    'college': ('college', 'dkyst'),
    'applicable_age': ('applicable age', 'vuqdwy mez'),
    'from': ('from', 'vksj ls'),
    'to': ('to', 'dks'),
    'media_type': ('media type (check all that apply)', 'fefM;k izdkj ykxq gksus okykksa dks fpUfgr djsa'),
    'video': ('video', 'pyfp='),
    'recorded_by_Plextor': ('recorded by Plextor', 'IysDlVj ls fjdZkfZMr'),
    'recorded_by_webcam': ('recorded by webcam', 'osscdssSSSejs ls fjdZkfZMr'),
    'recorded_by_CamStudio': ('recorded by CamStudio',
                              'dSeLVwfM;ks ls fjdZZkfZMr'),
    'audio_without_video': ('audio (without video)', 'vkokt (pyfp= fcuk)'),
    'images': ('images', 'fp='),
    'documents': ('documents', 'ys[k'),
    'other_type': ('other type (specify)', 'vU; izzdkj crk;sa'),
    'video_resolution': ('video resolution (width in pixels)', 'XXX'),
    'content_duration': ('content duration', 'XXX'),
    'hours': ('hours', '?kaVss'),
    'minutes': ('minutes', 'feuV'),

    'village_operations': ('Village School Operations',
                           'xzkehu ldwy lafdz;k'),
    'data': ('data', 'ikB'),
    'browse_repository': ('browse the content repository',
                          "dks'k ds vUnj ns[ksa"),
    'list_recent': ('list the most recently added content',
                    'lCkls u;h ikB ns[ksa'),
    'search': ('Search', '[kksTk'),
    'key_search': ('key word search', "'kCn [kksTk"),
    'search_author': ('search by author', 'jp;srk [kksTk'),
    'advanced_search': ('advanced search', 'mPp [kksTk'),
    'requests': ('Requests', 'fuosnu'),
    'manage_my_requests': ('manage requests of data I want sent to me', 
                           'vkids bPNqd ikB dh ikB ns[ksa'),
    'browse_submitted': ('browse the content I want submitted',
                         'Tkek dh xb phTksa dh fyLV n[ksa'),
    'discs': ('Discs', 'MfLd'),
    'prepare_data': ('prepare data for an outgoing disc',
                     'u;h MfLd ds fy, ikB Rkb;kj djsa'),
    'burn_outgoing': ('burn an outgoing disc', 'u;h MfLd cukb;sa'),
    'administration': ('Administration', 'lapkYkUk'),
    'clear_temp': ('clear temporary storage space',
                   'vYidkyh; LFku [kyh djsa'),
    'clear_repository': ('clear all repository data', "dks'k [kyh djsa"),
    'enter_key_words': ('Enter the keywords of interest', "bPNqd 'kCn"),
    'match_all': ('Match all words', "lkjs 'kCn feyus pkfg,"),
    'match_any': ('Match any word', "dksb 'kCn feyuk pkfg,"),
    'enter_author': ('Enter author name', 'jp;srk dk uke'),
    'required_fields': ('Required fields', "vko';d"),
    'executables': ('executables', 'XXX'),
    'slideshows': ('slideshows', 'XXX'),
    'plays': ('plays', 'XXX'),
    'teacher_training': ('teacher_training', 'XXX'),
    'content_alias': ('content alias', 'XXX'),
    'created_by_ProShow': ('created by ProShow', 'XXX'),
    'related_content': ('related content', 'XXX'),
    'recorded_by_Mustek': ('recorded by Mustek', 'XXX'),
    'staff_training': ('staff_training', 'XXX'),
    'has_subtitle': ('has subtitle', 'XXX'),
    'with_vocabulary': ('with vocabulary', 'XXX'),
    'textbook': ('textbook', 'XXX'),
    'course_materials': ('course_materials', 'XXX'),
    'support_software': ('support_software', 'XXX'),
    'monitoring': ('monitoring', 'XXX'),
    'requests': ('requests', 'XXX'),
    'extracted_by_firewire': ('extracted by firewire', 'XXX'),
    'interview': ('interview', 'XXX'),
    'recorded_by_Aiptek': ('recorded by Aiptek', 'XXX'),
    'kannada': ('Kannada', 'XXX'),
    'tamil': ('Tamil', 'XXX'),
    'bengali': ('Bengali', 'XXX'),
    'marathi': ('Marathi', 'XXX'),
    'punjabi': ('Punjabi', 'XXX'),
    'telegu': ('Telegu', 'XXX'),
    'gujarati': ('Gujarati', 'XXX'),
    'kashmiri': ('Kashmiri', 'XXX'),
    'uploaded_by_site': ('uploaded by (site name)', 'XXX'),
    'environmental_science': ('environmental science', 'XXX'),
    'cache': ('cache', 'XXX'),
    'sticky': ('sticky', 'XXX'),
    'show': ('show', 'XXX'),
    'copyrighted': ('copyrighted', 'XXX'),
    'discreet': ('discreet', 'XXX'),
    'recorded_from_TV': ('recorded from TV', 'XXX'),
    'commerce': ('commerce', 'XXX'),
    'data_size': ('data size', 'XXX'),
    'date_and_time': ('date and time', 'XXX'),
    'documentary': ('documentary', 'XXX'),
    'other_TV': ('other TV', 'XXX'),
    'workshop': ('workshop', 'XXX'),
    'radio_program': ('radio program', 'XXX'),
    'visits': ('visits', 'XXX'),
    'geology': ('geology', 'XXX'),
    'nursing': ('nursing', 'XXX'),
    'practicals': ('practicals', 'XXX'),
    'experiments': ('experiments', 'XXX'),
    'community_training': ('community training', 'XXX'),
    'reproductive_health': ('reproductive health', 'XXX'),
    'public_awareness': ('public awareness', 'XXX'),
    'health_care': ('health care', 'XXX'),
    'children_health': ('children health', 'XXX'),
    'women_rights': ('women rights', 'XXX'),
    'VHS_tape_digitized': ('VHS tape digitized', 'XXX'),
    'from_YouTube': ('from YouTube', 'XXX'),
    'seconds': ('seconds', 'XXX'),
    'compilation': ('compilation', 'XXX'),
    'supplementary': ('supplementary', 'XXX'),
    'chapter_number': ('chapter number', 'XXX'),
    'children_program': ('children program', 'XXX'),
    'lesson_plan': ('lesson plan', 'XXX'),
    'test': ('test', 'XXX'),
    'culture_and_customs': ('culture and customs', 'XXX'),
    'enhanced_downloads': ('enhanced downloads', 'XXX'),
    'urdu': ('Urdu', 'XXX'),
    'nepali': ('Nepali', 'XXX'),
}
